Group chat - Progress halted, foreseeable future
Progress has been halted due to EF Core exceptions, likely due to how the DBContext was configured. It's likely that a DBContextFactory approach would be more advisable given the real-time nature of the application.

KNOWN ISSUE:
- Adding message to database within Group Chats will cause an exception, leading SignalR to cease Real-Time message functions (hereby referred to as "RT-MF"), even after reloading.

STEPS TO RECREATE:
1) Select a Course's group chat
--- (NOTE: RT-MF will work upon multiple clients initially)
2) Switch to a different course
3) Switch back to initial course
4) Select the initial Group Chat
5) [[POINT OF EXCEPTION]] Send a message to Group Chat
--- This is the point where it breaks the RT-MF

EXCEPTION DETAILS (Truncated):

fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '9yAPZYyigOJIzdFtSqlf9vh757ZUSM-c-Vrc67TC3LA'.
      System.Exception: Failed to add message to database
       ---> System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
         at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<<ExecuteAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at StudentTimeTrackerApp.Services.MessagePageService.AddMessageToDatabaseAsync(String senderId, String recipientId, Int32 courseId, String body) in [[REDACTED]]\SE1_StudentTimeTrackerApp\Services\MessagePageService.cs:line 547
[[....]]